# Generated by Django 2.1 on 2019-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20190726_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='book/empty_cover.jpg', upload_to='book/'),
        ),
    ]
