# Generated by Django 2.1 on 2019-08-01 06:34

import bookstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='book/empty_cover.jpg', upload_to=bookstore.models.cover_upload_path),
        ),
    ]
